#!/bin/bash

user_id=$(id -u)
component=mysql
log=/tmp/{component}.log

if [ $user_id -ne 0 ]; then 
  echo -e "\e[33m you needs to be perform as root user \e[0m"
  echo -e "EXAMPLE  sudo <file_name>"
  exit 1
fi


statusus() {
    if [ $? -eq 0 ]; then
      echo -e "\e[32m sucess \e[0m"
    else
      echo -e "\e[33 failure \e[0m" 
      exit 2  
    fi
}



echo -n "installing my-sql repo:  " 
curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/stans-robot-project/mysql/main/mysql.repo &>> ${log}
yum install mysql-community-server -y &>> ${log}
systemctl enable mysqld &>> ${log}
systemctl start mysqld &>> ${log}
statusus $?

# This should happen only once and that too for the first time, when it runs for the second time, jobs fails.
echo -n "Extracting the default mysql root password :"
DEFAULT_ROOT_PASSWORD=$(grep 'temporary password' /var/log/mysqld.log | awk -F '{print $NF}')
statusus $?

echo "show databases;" | mysql -uroot -pRoboShop@1 &>>  ${log}
if [ $? -ne 0 ]; then 
    echo -n "Performing default password reset of root account:"
    echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1'" | mysql  --connect-expired-password -uroot -p$DEFAULT_ROOT_PASSWORD &>>  ${log}
    status $?
fi 

echo "show plugins;" | mysql -uroot -pRoboShop@1 | grep validate_password  &>>  ${log}
if [ $? -eq 0 ]; then 
    echo -n "Uninstalling Password-validate plugin :"
    echo "uninstall plugin validate_password" | mysql -uroot -pRoboShop@1 &>>  ${log}
    status $?
fi 


echo -n "Downloading the $component schema:"
curl -s -L -o /tmp/${component}.zip "https://github.com/stans-robot-project/${component}/archive/main.zip"
status $? 

echo -n "Extracting the $component Schema:"
cd /tmp  
unzip -o /tmp/${component}.zip   &>> $log
status $? 

echo -n "Injecting the schema:"
cd ${component}-main 
mysql -u root -pRoboShop@1 <shipping.sql     &>>  ${log} 
status $? 


echo -e "\e[35m ${component} Installation Is Completed \e[0m \n