#!/bin/bash

set -e

user_id=$(id -u)
component="user"
appuser="roboshop"
log="/tmp/${component}.log"

if [ $user_id -ne 0 ]; then
  echo -e "\e[32mScript must be executed by the root user or with sudo privileges\e[0m"
  exit 1
fi

statusfunction() {
    if [ $? -eq 0 ]; then
       echo -e "\e[33mSuccessfully installed\e[0m"
    else
       echo -e "\e[31mInstallation failed\e[0m"
       exit 1
    fi
}

echo -e "\e[35mConfiguring ${component}\e[0m"

echo -n "Installing ${component}: "
curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
statusfunction $?

echo -n "Installing Node.js: "
yum install nodejs -y
statusfunction $?

id ${appuser} &>> ${log}
if [ $? -ne 0 ]; then
  echo -n "Creating application user account: "
  useradd ${appuser}
  statusfunction $?
fi    

echo -n "Downloading the ${component}: "
curl -s -L -o /tmp/user.zip "https://github.com/stans-robot-project/user/archive/main.zip"
unzip  /tmp/user.zip 
statusfunction $?

echo -n "Copying the ${component} to ${appuser} home directory: "
cd /home/${appuser}
mv user-main  user
chown -R ${appuser}:${appuser} /home/${appuser}/${component}/
statusfunction $?

echo -n "Generating the ${component} artifacts: "
cd /home/${appuser}/${component}/
npm install 
statusfunction $?
 
echo -n "Updating the ${component} systemd file: "
sed -i "s/MONGO_ENDPOINT/mongodb.roboshop/g"  /home/roboshop/user/systemd.service
sed -i "s/REDIS_ENDPOINT/172.31.8.190/g"  /home/roboshop/user/systemd.service
mv /home/roboshop/user/systemd.service /etc/systemd/system/user.service
statusfunction $?

echo -n "Starting the user service: "
systemctl daemon-reload
systemctl start user
systemctl enable user
statusfunction $?
