#!/bin/bash

set -e

user_id=$(id -u)
component="user"
appuser="roboshop"
log="/tmp/${component}.log"

if [ $user_id -ne 0 ]; then
  echo -e "\e[32mScript must be executed by the root user or with sudo privileges\e[0m"
  exit 1
fi

statusfunction() {
    if [ $? -eq 0 ]; then
       echo -e "\e[33mSuccessfully installed\e[0m"
    else
       echo -e "\e[31mInstallation failed\e[0m"
       exit 1
    fi
}
echo -n "downloading nodejs repo : "
curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
yum install nodejs -y
statusfunction $?

echo "adding roboshop user acc"
useradd roboshop
cd /home/roboshop
statusfunction $?

curl -s -L -o /tmp/user.zip "https://github.com/stans-robot-project/user/archive/main.zip"
cd /home/roboshop
unzip /tmp/user.zip
statusfunction $?

echo -n "moving the info  roboshop: "
mv user-main user
chown +R *
cd /home/roboshop/user
npm install
statusfunction $?

echo -n "coping info to system service file : "

sed -ie "s/REDIS_ENDPOINT/redis.roboshop/g" /home/roboshop/user/systemd.service
sed -ie "s/MONGO_ENDPOINT/mongodb.roboshop/g" /home/roboshop/user/systemd.service
statusfunction $?

echo -n "startting the system service file : "
systemctl daemon-reload
systemctl start user
systemctl enable user


# mv /home/roboshop/user/systemd.service /etc/systemd/system/user.service
# systemctl daemon-reload
# systemctl start user
# systemctl enable user

/etc/nginx/default.d/roboshop.conf

# vim /etc/nginx/default.d/roboshop.conf

Once the USER IP Address is added, restart the service

# systemctl daemon-reload
# systemctl restart nginx